version: '3'

services:
  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      PUID: 1000
      GUID: 1000
      UMASK_SET: '0022'
      TZ: America/Los_Angeles
    network_mode: host
    restart: unless-stopped
    volumes:
      - /config/mugi-server/deluge/config:/config
      - /media/tea/torrents:/torrents

  flickrsyncr:
    image: primederivation/flickrsyncr:latest
    container_name: flickrsyncr
    environment:
      TZ: America/Los_Angeles
    network_mode: host
    user: 1000:1000
    volumes:
      - /config/mugi-server/flickrsyncr/config:/config
      - /media/tea/images/wallpapers:/data/wallpapers
 
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    environment:
      TZ: America/Los_Angeles
      PLEX_UID: 1000
      PLEX_GID: 1000
    network_mode: host
    restart: unless-stopped
    volumes:
      - /config/mugi-server/plex/config:/config
      - /config/mugi-server/plex/transcode:/transcode
      - /media/tea/music:/data/music
      - /media/tea/pictures:/data/pictures
      - /media/tea/video:/data/video

