version: '3'

services:
  caddy:
    image: abiosoft/caddy
    container_name: caddy
    environment:
      CADDYPATH: /etc/caddycerts
    network_mode: host
    volumes:
      - /config/mugi-server/caddy/caddycerts:/etc/caddycerts
      - /config/mugi-server/caddy/Caddyfile:/etc/Caddyfile
      - /config/mugi-server/caddy/srv:/srv

  deluge:
    image: linuxserver/deluge
    container_name: deluge
    environment:
      PUID: 1000
      GUID: 1000
      UMASK_SET: '0022'
      TZ: America/Los_Angeles
    healthcheck:
      test: curl -f http://localhost:8112/ || exit 1
      interval: 1m
      timeout: 3s
      retries: 5
    network_mode: host
    restart: unless-stopped
    volumes:
      - /config/mugi-server/deluge/config:/config
      - /media/tea/torrents:/torrents

  flickrsyncr:
    image: primederivation/flickrsyncr:latest
    container_name: flickrsyncr
    environment:
      TZ: America/Los_Angeles
    network_mode: host
    user: 1000:1000
    volumes:
      - /config/mugi-server/flickrsyncr/config:/config
      - /media/tea/images/wallpapers:/data/wallpapers
 
  plex:
    image: plexinc/pms-docker:plexpass
    container_name: plex
    environment:
      TZ: America/Los_Angeles
      PLEX_UID: 1000
      PLEX_GID: 1000
    healthcheck:
      test: curl -f http://localhost:32400/web/index.html || exit 1
      interval: 1m
      timeout: 3s
      retries: 5
    network_mode: host
    restart: unless-stopped
    volumes:
      - /config/mugi-server/plex/config:/config
      - /config/mugi-server/plex/transcode:/transcode
      - /media/tea/music:/data/music
      - /media/tea/pictures:/data/pictures
      - /media/tea/video:/data/video

